name: level5_Navigation_12_21

task_type: "navigation_test_weizi"
controller_type: "navigation"

mode: "collect"

usd_path: "assets/navigation_lab/navigation_lab_01/lab.usd"

max_episodes: 100

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

task:
  max_steps: 4000
  navigation_config_path: "config/navigation/navigation_assets_12_14.yaml"
  goal_pairs:
    - start: [-5.59, 0.98, 1.57]  # [x, y, theta] - 起点坐标和朝向角度
      end: [-0.35, -0.18, 1.57]   # [x, y, theta] - 终点坐标和朝向角度
    - start: [-0.35, -0.18, 0] # [x, y, theta] - 起点坐标和朝向角度
      end: [-5.59, 0.98, 0]    # [x, y, theta] - 终点坐标和朝向角度
  max_linear_speed: 0.04
  max_angular_speed: 1.5
  position_threshold: 0.08
  angle_threshold: 0.1

cameras:
  - prim_path: "/World/Ridgebase/base_link/Camera"
    name: "front_camera"
    resolution: [256, 256]
    image_type: "rgb"

  - prim_path: "/World/Ridgebase/base_link/Camera_02"
    name: "wrist_camera"
    resolution: [256, 256]
    clipping_range: [1, 5]
    image_type: "rgb"
  
  - prim_path: "/World/Ridgebase/base_link/Camera_01"
    name: "top_camera"
    resolution: [256, 256]
    image_type: "rgb"



robot:
  type: "ridgebase"
  position: [0.0, 0.0, 0.0]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}