name: Level3_open

task_type: "openclose"
controller_type: "open"

mode: "collect"
usd_path: "assets/chemistry_lab/lab_001/lab_001.usd"

max_episodes: 100

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

  is_test_material: False

task:
  max_steps: 1000
  obj_paths:
    - path: "/World/DryingBox_01"
      position_range:
        x: [0.72, 0.77]
        y: [0.0, 0.15]
        z: [0.78, 0.78]
    - path: "/World/DryingBox_02"
      position_range:
        x: [0.72, 0.77]
        y: [-0.05, 0.010]
        z: [0.78, 0.78]
    - path: "/World/MuffleFurnace"
      position_range:
        x: [0.65, 0.70]
        y: [-0.05, 0.010]
        z: [0.78, 0.78]
  material_paths:
    - path: "/World/table/surface"
      materials:
        - "/World/Looks/Material1_plastic_dark_blue"
        - "/World/Looks/Material2_wood"
        - "/World/Looks/Material3_plastic_dark_green"
        - "/World/Looks/Material4_plastic_light_white"
        - "/World/Looks/Material5_black"
      test_materials:
        - "/World/Looks/Material6_plastic_light_blue"
        - "/World/Looks/Material7_stainless"

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [-0.7, 1.4, 1.4]
    resolution: [256, 256]
    focal_length: 2
    orientation: [-0.2297, -0.18336, 0.59631, 0.74701]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [-1, -0.1, 3.6]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.69035, 0.15304, -0.15304, -0.69035]
    image_type: "rgb"

  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_3"
    resolution: [256, 256]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
